#!/usr/bin/env bash

if [[ -n $(git status -s) ]]; then
   echo "working tree modified. aborts deploy."
   exit 1
fi

# Verify correct branch
git checkout develop

# Build new files
stack exec site rebuild

# Get previous files
git fetch --all
git checkout master

# Overwrite existing files with new files
cp -a _site/. ../blog/

# Commit
git add -A
git commit -m "Publish."

# Push
git push origin master:master

# Restoration
git checkout develop
